algoritmo "Combinações"
// Função :
// Autor :Pedro Albuquerque
// Data : 21/09/2020
// Seção de Declarações 
var
x, y:inteiro
inicio
// Seção de Comandos
para x:=1 ate 3 faca //Nessa questão usasse o símbolo := (de) invês de <-(recebe)
//Assim, ele não diz que o x recebe 1 e vai até 3
//Ele lê que o x vai DE 1 até 3
     para y:=1 ate 3 faca
          escreval(x,y)
     fimpara
fimpara
fimalgoritmo
