algoritmo "Sabendo a Idade"
// Função :
// Autor : Pedro Albuquerque
// Data : 16/09/2020
// Seção de Declarações 
var
  ano_atual, ano_nasc, idade:inteiro
inicio
// Seção de Comandos
   escreva("Em que ano nós estamos? ")
   leia(ano_atual)
   escreva("Agora escreva em que ano você nasceu: ")
   leia(ano_nasc)
   idade<-ano_atual-ano_nasc
   escreva("Então, a sua idade é ", idade, " anos.")
fimalgoritmo
