algoritmo "Soma de Números"
// Função :
// Autor :
// Data : 15/09/2020
// Seção de Declarações 
var
  numero1, numero2, total: inteiro
inicio
Escreva("Vamos somar dois numeros inteiro. Digite o primeiro numero inteiro: ")
leia(numero1)
Escreva("Agora digite o segundo número inteiro: ")
leia(numero2)
total<-numero1+numero2
Escreva(" O valor da soma de " numero1, "e ", numero2, " é: ", total, "." )
fimalgoritmo
