algoritmo "Comparando Números"
// Função :
// Autor : Pedro Albuquerque
// Data : 16/09/2020
// Seção de Declarações 
var
   A,B,C:inteiro
inicio
// Seção de Comandos
   A<-2
   B<-3
   C<-5
   escreval(A>B)//Operador > maior que
   escreval(A<B)//Operador < menor que
   escreval(C>=B-A)//Operador >= maior ou igual a
   escreval(A+B<=C)//Operador <= menor ou igual a
   escreval(A=B)//Operador = igual
   escreva(A<>B)//Operador <> diferente
fimalgoritmo
